version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      
artifacts:
  files:
    - 'target/your-rights-0.0.2-SNAPSHOT.jar'

cache:
  paths:
  - '/root/.m2/**/*'