version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'target/your-rights.jar'

cache:
  paths:
  - '/root/.m2/**/*'