version: 0.2

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the protest jar
    - mvn install
      
artifacts:
  files:
    - 'target/your-rights-0.0.2-SNAPSHOT.jar'

cache:
  paths:
  - '/root/.m2/**/*'