
## AWS
#cloud.aws.region.auto: false
#cloud.aws.region.static: eu-west-1

## default connection pool
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
  datasource:
    platform: postgres
    url: jdbc:postgresql://database-yourrights.cbyqx4iadwwj.us-east-2.rds.amazonaws.com:8181/yourrightsdb
    username: yourrightsadmin
    password: yourrightsadmin
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        host: smtp.gmail.com
        port: 465
        user: anaromanrodriguez1987@gmail.com
        password: 100061851
        transport:
          protocol: smtp
        smtp:
          auth: false
          socketFactory:
            port: 25
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtp
    
config:
  maxNumPage: 20
  security:
    secretKey: 'krlAaJ714XQm6V9iofE4'
    encryptPwd: 'password'
    encryptSalt: 'salt'
    