
## AWS
#cloud.aws.region.auto: false
#cloud.aws.region.static: eu-west-1

## default connection pool
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
  datasource:
    platform: postgres
    url: jdbc:postgresql://database-yourrights.cbyqx4iadwwj.us-east-2.rds.amazonaws.com:8181/yourrightsdb
    username: yourrightsadmin
    password: yourrightsadmin

#spring.mail.host: smtp.gmail.com
#spring.mail.port: 465
#spring.mail.username: anaromanrodriguez1987@gmail.com
#spring.mail.password: 100061851
#spring.mail.properties.mail.smtp.auth: true
#spring.mail.properties.mail.smtp.connectiontimeout: 5000
#spring.mail.properties.mail.smtp.timeout: 5000
#spring.mail.properties.mail.smtp.writetimeout: 5000
#spring.mail.properties.mail.smtp.socketFactory.port: 465
#spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactor

config:
  maxNumPage: 20
  security:
    secretKey: 'krlAaJ714XQm6V9iofE4'
    encryptPwd: 'password'
    encryptSalt: 'salt'
    